# Profile section
profile:
  first_name: Cooper
  last_name: Varela
  picture: https://cdn.discordapp.com/attachments/850915802017431572/947620237791096872/CyberFusion2022_055.jpg # Hosted picture
  # picture: static/img/rodo_2021.png  # Local picture
  contact:
    address_one: Northern Virgina 
    address_two:
    phone: ‪(703) 634-9272‬
  email: cooper.varela+www@gmail.com
  description: |
    Cyber security student with a passion for technology, seeking to improve my skills and help companies fill the nation's cyber security gap.


# Social section
social:
  website: http://www.coopervarela.com
  github: https://github.com/coopervarela
  twitter: 
  linkedin: https://www.linkedin.com/in/cooper-varela-5b367218a
  facebook:
  dev: https://devpost.com/cooper-varela?ref_content=user-portfolio&ref_feature=portfolio&ref_medium=global-nav
  medium: 


# Experience section
experience:
  item7: 
    position: PatriotHacks Hackathon
    company: GMU
    from: March 2022
    to: March 2022
    description: Competed in the George Mason University PatriotHacks event where my team won 1st. In the Salesforce track and 3rd. In the sustainability track.
    link: https://devpost.com/software/gmu-ghg-dashboard#updates
  item6: 
    position: Cyber Fusion Competitor 
    company: VMI 
    from: February 2022
    to: February 2022
    description: Through LFCC I competeted on behalf of the college in the VMI Commonwealth Cyber Fusion competition where my team came in 1st. Place.
    link: https://www.vmi.edu/about/conferences/cyberfusion/
  item5:
    position: Print & Marketing Associate
    company: Staples
    from: June 2021
    to: July 2021
    description: >
      Responsibilities: Organizing entire department while supporting customer needs, troubleshooting printing systems in support of customer demand, using technology to solve the needs of customers, and educating customers on technical solutions.
  item4:
    position: Team Competitor
    company: NCL/Cyber Skyline
    from: February 2021
    to: April 2021
    description: >
      Participated in the team based National Cyber League Capture the Flag where I competed in categories such as log analysis, OSI, cryptography, forensics and, network traffic analysis with my schools Cybersecurity competition team.
    link: http://cyberskyline.com/report/RV9TVTTBR60J
  item3:
    position: Individiual Competitor 
    company: NCL/Cyber Skyline
    from: February 2021
    to: April 2021
    description: >
      Participated in the individual National Cyber League Capture the Flag event where I competed in categories such as log analysis, OSI, cryptography, forensics and, network traffic analysis.	
    link: http://cyberskyline.com/report/DD3N71AX6DF3
  item2:
    position: Online contractor 
    company: Self employed
    from: January 2020
    to: August 2020
    description: >
      Contracted with online clients to create technical documentation of various design patterns in video game development. Responsibilities: Finding and securing client base, and meeting customer deadlines with multiple deliverables simultaneously, testing and reviewing software products.
  item1:
    position: Junior Baker
    company: Blue Ridge Baking Company
    from: June 2019
    to: August 2019
    description: >
      This was my first exposure to a work environment. In this position I was tasked with assisting the staff with cleaning the kitchen, packaging products, and storing products. This was the first job I was expose to a work environment. In this position I was tasked with assisting the staff with cleaning the kitchen, packaging products, and storing products. 
  reference: https://docs.google.com/document/d/1_fel546-c7uan85yLRtzodgPdj9Uof6f/edit?usp=sharing&ouid=114479504748287987728&rtpof=true&sd=truehttps://docs.google.com/document/d/1_fel546-c7uan85yLRtzodgPdj9Uof6f/edit?usp=sharing&ouid=114479504748287987728&rtpof=true&sd=true


# Education section
education:
  item2:
    institution: Laurel Ridge Community College
    program: Associate of Applied Science in Cybersecurity 
    description: Participated on my schools Technology Competition team where I attended several Capture the Flag events.
    from: August 2020
    to: Expected May 2023
  item3:
    institution: HomeLab 
    program: Home
    description: I have a homelab that I run VMware on where I learn OpenShift, Ansible, and Git.
    from: 2021
    to: Present
  item4:
    institution: Hack the Box Academy 
    program: Offensive/Defensive/General 
    description: Since March, I have studied offensive hacking, defensive security, and other general IT/Network concepts. 
    from: March 2022
    to: Present
  item5:
    institution: Pluralsight
    program: Networking/Secuirty/Python
    description: Since 2020 I have completed several Pluralsight courses including, Network Security Basics, Practical Networking, Python, and Ethical Hacking.
    from: January 2020
    to: Present
  item6:
    institution: Homeschool
    program: High School diploma 
    description: During my last year of school I dual enrolled into Laurel Ridge Community College.
    from: August 2017
    to: May 2021
  reference: https://docs.google.com/document/d/1_fel546-c7uan85yLRtzodgPdj9Uof6f/edit?usp=sharing&ouid=114479504748287987728&rtpof=true&sd=true



# Community section:
community: 
  item2:
    institution: The Commonwealth Cyber Initiative
    program: CCI Cyber Camp
    description: I was selected for an invitation to the second annual CCI Cyber Camp. After completing the qualifying event where I was tasked with completing several challenges including cryptography, networking, reverse engineering, and, web exploitation. During the camp, I was able to attend lectures on wireless communication networks, artificial intelligence, and data analytics. After the lectures, I was able to participate in hands-on workshops where I was able to use tools such as jmp to create a working 4G network and group presentations on data analytics as well as AI. 
    from: June 2022
    to: June 2022
    link: https://cyberinitiative.org/cci-news/2022/cci-hosts-the-2022-cci-cyber-camp.html
  item3:
    institution: The Commonwealth Cyber Initiative
    program: Innovation Boot Camp
    description: Attended the first CCI Innovation Boot Camp where I was tasked with developing and presenting the solution to a realworld enterprise sponsored problem. The task we were assigned was to develop multiple honeypots for our sponsors network to capture malware.
    from: January 2022
    to: January 2022
    link: https://cyberinitiative.org/events-programs/2021/cci-innovation-bootcamp.html
  item4:
    institution: Laurel Ridge Community 
    program: Technology Competition Team
    description: Participated as an active member of the Technology Competition team were I attended several capture the flag competitions.
    from: January 2021
    to: Present
    link:
  reference: https://docs.google.com/document/d/1_fel546-c7uan85yLRtzodgPdj9Uof6f/edit?usp=sharing&ouid=114479504748287987728&rtpof=true&sd=true


# Skills section
tools:
  # Consider that the following are fa icons:
  #   https://fontawesome.com/icons?d=gallery&s=brands
  - python
  - github
  - slack
  - linux
  - redhat
  - windows
  
extra_skills:
  # - Facebook Messenger, Telegram, and SMS bots
  - Networking 
  - Wireshark
  - Nmap
  - WSL
  - Kali
  - OpenVPN
  - VMware
  - Openshift
  - Podman
  - SalesForce
  - Agile
  - Ansible
  - BASH
  - Networks
  - RSA, PKI, PGP Encryption
  - OSForensics
  - Autopsy
  - FTK imager


# Talks and workshops section
workshops:
  item8: 
    event: CCI Cyber Camp
    Workshop: Workshop - 2022
    link: https://cyberinitiative.org/cci-news/2022/cci-hosts-the-2022-cci-cyber-camp.html
    material: https://cyberinitiative.org/events-programs/2022/cybercamp-2022.html
  item9: 
    event: CCI Innovation Boot Camp
    workshop: Workshop - 2022
    link: https://cyberinitiative.org/events-programs/2021/cci-innovation-bootcamp.html
    material: 
  item10:
    event: NCL + CompTIA Preparing You for a Career in Cybersecuity 
    workshop: Talk - 2022
    link: https://www.crowdcast.io/m?t=38ef730a20dbbbdb3cdd4d0bcd58cbca:a5887f1c1a5ebf8a8493a5299d23c8d7491387ee8ac78ba9b98e89b060c77311f86c965b0de170ba38e669d6bfc33427
    material: 
  item11:
    event: National Cyber League x CrowdStrike Webinar
    workshop: Talk – 2022
    link: https://crowdstrike.zoom.us/webinar/register/WN_fi8OYhubQba5CGAMgWUA4ghttps://crowdstrike.zoom.us/webinar/register/WN_fi8OYhubQba5CGAMgWUA4g
    material: 
  item12: 
    event:  CNAPP with ESG Research & Palo Alto Networks
    workshop: Talk -2022
    link: https://www.linkedin.com/video/live/urn:li:ugcPost:6904092730595639296/
    material:
  reference: https://docs.google.com/document/d/1_fel546-c7uan85yLRtzodgPdj9Uof6f/edit?usp=sharing&ouid=114479504748287987728&rtpof=true&sd=true

# Projects section
projects:
  item1:
    title: Flask_WebApp_DemoFlask_WebApp_Demo
    subtitle: Flask/Bootstrap docker image
    description: Web framework image for Docker.
    github: https://github.com/DankeSaurus
    link: https://github.com/DankeSaurus/Flask_WebApp_Demo.git
    img: https://cdn.discordapp.com/attachments/850915802017431572/972530439271092314/unknown.png
    tags: [Flask, Python, Gunicorn, Bootstrap, Docker]
  


# Certifications and awards section
awards:
  - 1st. Place - Community College Division - VMI Cyber Fusion 2022
  - Network Management and Operations - Pluralsight 2022
  - Introduction to Enterprise Network Infrastructure - Pluralsight 2021
  - Network Concepts and Protocols - Pluralsight 2021
  - Python The Big Picture - Pluralsight 2020
  - Ethical Hacking Scanning Networks - Pluralsight 2020
  - Ethical Hacking Reconnaissance/Footprinting - Pluralsight 2020
  - Ethical Hacking Understanding Ethical Hacking - Pluralsight 2020
  - Network Penetration Testing Using Python and Kali Linux - Pluralsight 2020
  - Practical Networking - Pluralsight 2020
  - Network Troubleshooting and Tools - Pluralsight 2020
  - Network Security Basics - Pluralsight 2020
  - Introduction to Enterprise Network Infrastructure - Pluralsight 2020
  - Networking Concepts and Protocols - Pluralsight 2020